---
exclude_paths:
    - "README.md"
    - "Readme.md"
    - "readme.md"
    - "**/README.md"
    - "**/Readme.md"
    - "**/readme.md"
    - "src/test-images/**"
    - "node_modules/**"
    - "tmp/**"
