#!/usr/bin/env node
// Local dev ramp-up script. Deliberately dependency-free (only core Node modules) so it can
// run before `pnpm install` has ever succeeded. Safe to re-run -- every step is idempotent.
//
// Usage:
//   node scripts/setup.mjs                 # deps + seed names DB (nedb only, no MySQL)
//   node scripts/setup.mjs --with-mysql    # also start docker compose MySQL + run setup-db
//   node scripts/setup.mjs --skip-seed     # skip the network-dependent name-seeding step
//   node scripts/setup.mjs --skip-install  # skip `pnpm install` (e.g. already ran it)

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, "..");

const args = process.argv.slice(2);
const flags = {
    withMysql: args.includes("--with-mysql"),
    skipSeed: args.includes("--skip-seed"),
    skipInstall: args.includes("--skip-install")
};

const steps = [];
function step(title, fn) {
    steps.push({ title, fn });
}

function run(cmd, cmdArgs, opts = {}) {
    console.log(`  $ ${cmd} ${cmdArgs.join(" ")}`);
    const result = spawnSync(cmd, cmdArgs, {
        cwd: repoRoot,
        stdio: "inherit",
        shell: process.platform === "win32",
        ...opts
    });
    return result.status === 0;
}

function checkNodeVersion() {
    const major = Number(process.versions.node.split(".")[0]);
    if (major < 20) {
        console.warn(
            `  ⚠ Node ${process.versions.node} detected -- this project targets Node >=20. Things may not work.`
        );
        return false;
    }
    console.log(`  ✓ Node ${process.versions.node}`);
    return true;
}

function checkPnpm() {
    const result = spawnSync("pnpm", ["--version"], {
        cwd: repoRoot,
        shell: process.platform === "win32"
    });
    if (result.status !== 0) {
        console.warn(
            "  ⚠ pnpm not found. Run `corepack enable` or `npm i -g pnpm`, then re-run this script."
        );
        return false;
    }
    console.log(`  ✓ pnpm ${String(result.stdout).trim()}`);
    return true;
}

function copyIfMissing(fromRel, toRel, note) {
    const from = path.join(repoRoot, fromRel);
    const to = path.join(repoRoot, toRel);
    if (fs.existsSync(to)) {
        console.log(`  ✓ ${toRel} already exists, leaving it alone`);
        return;
    }
    if (!fs.existsSync(from)) {
        console.warn(`  ⚠ ${fromRel} not found, can't create ${toRel}`);
        return;
    }
    fs.copyFileSync(from, to);
    console.log(`  ✓ created ${toRel}${note ? ` (${note})` : ""}`);
}

// With --with-mysql the point is a working local MySQL out of the box, so write credentials
// that actually match docker-compose.yml's defaults instead of the generic "..." template.
function writeMysqlSecureConfig() {
    const to = path.join(repoRoot, "secure.config.cjs");
    if (fs.existsSync(to)) {
        console.log("  ✓ secure.config.cjs already exists, leaving it alone");
        return;
    }
    const envExample = path.join(repoRoot, ".env.example");
    const env = fs.existsSync(path.join(repoRoot, ".env"))
        ? path.join(repoRoot, ".env")
        : envExample;
    const vars = Object.fromEntries(
        fs
            .readFileSync(env, "utf8")
            .split("\n")
            .map((line) => line.trim())
            .filter((line) => line && !line.startsWith("#"))
            .map((line) => line.split("="))
    );
    const contents = `// Generated by scripts/setup.mjs --with-mysql -- matches docker-compose.yml's defaults.
module.exports = {
    rds: {
        host: "127.0.0.1",
        port: ${Number(vars.MYSQL_PORT) || 3306},
        database: "${vars.MYSQL_DATABASE || "MtgCardCatalog"}",
        user: "root",
        password: "${vars.MYSQL_ROOT_PASSWORD || "root"}"
    }
};
`;
    fs.writeFileSync(to, contents);
    console.log("  ✓ created secure.config.cjs matching docker-compose.yml defaults");
}

step("Checking Node version", checkNodeVersion);
step("Checking pnpm", checkPnpm);

if (!flags.skipInstall) {
    step("Installing dependencies", () => run("pnpm", ["install"]));
}

step("Installing Git hooks", () => run("node", ["scripts/install-git-hooks.mjs"]));

step("Setting up local config files", () => {
    if (flags.withMysql) {
        writeMysqlSecureConfig();
    } else {
        copyIfMissing(
            "secure.config.template.cjs",
            "secure.config.cjs",
            "only needed if you use --storage-adapter rds -- edit before use, has placeholder values"
        );
    }
    copyIfMissing(
        "mtg.config.example.json",
        "mtg.config.json",
        "optional, defaults work fine without it"
    );
    return true;
});

if (!flags.skipSeed) {
    step("Seeding local card names DB (needs network access to Scryfall)", () => {
        const ok = run("node", ["./src/db-local/bulk-insert.mjs"]);
        if (!ok) {
            console.warn(
                "  ✗ Required card-name seed failed. Scans will not work until seeding succeeds; fix the reported catalog/network error and rerun setup."
            );
        }
        return ok;
    });
} else {
    step("Skipping name-seed step (--skip-seed)", () => {
        console.warn(
            "  ⚠ Seed skipped. This is safe only when diagnostics already reports a healthy card-name index."
        );
        return true;
    });
}

if (flags.withMysql) {
    step("Starting local MySQL (docker compose)", () => {
        const composeUp = run("docker", ["compose", "up", "-d"]);
        if (!composeUp) {
            console.warn("  ⚠ `docker compose up` failed -- is Docker running?");
            return false;
        }
        return true;
    });

    step("Waiting for MySQL to become healthy", () => {
        for (let i = 0; i < 30; i += 1) {
            const check = spawnSync(
                "docker",
                ["inspect", "--format={{.State.Health.Status}}", "mtg-card-analyzer-mysql"],
                { cwd: repoRoot }
            );
            const healthStatus = String(check.stdout || "").trim();
            if (healthStatus === "healthy") {
                console.log("  ✓ MySQL is healthy");
                return true;
            }
            spawnSync(process.platform === "win32" ? "timeout" : "sleep", [
                process.platform === "win32" ? "/t 1" : "1"
            ]);
        }
        console.warn(
            "  ⚠ MySQL didn't report healthy in time -- check `docker compose logs mysql`"
        );
        return false;
    });

    step("Running setup-db (creates tables if missing)", () => {
        if (!fs.existsSync(path.join(repoRoot, "secure.config.cjs"))) {
            console.warn("  ⚠ secure.config.cjs missing, skipping setup-db");
            return false;
        }
        return run("pnpm", ["setup-db"]);
    });
}

console.log("\nSetting up MTG Card Analyzer local dev environment...\n");
let hadFailure = false;
for (const { title, fn } of steps) {
    console.log(`${title}...`);
    const ok = fn();
    if (!ok) {
        hadFailure = true;
    }
}

console.log("\nNext steps:");
console.log(
    "  node index.mjs scan ./test-images/PlatinumAngel.jpg          # identify without collection writes"
);
console.log(
    "  node index.mjs scan ./test-images/PlatinumAngel.jpg --query --enable-collection  # persist to nedb"
);
console.log(
    "  node scripts/verify-env.mjs                                      # sanity-check the environment"
);
console.log(
    "  pnpm check                                                       # full quality gate"
);
if (!flags.withMysql) {
    console.log(
        "  node scripts/setup.mjs --with-mysql                              # to also set up local MySQL"
    );
}

process.exit(hadFailure ? 1 : 0);
