on:
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: 'true'
          ACTION_MAIL: myuser@users.noreply.github.com
          ACTION_NAME: myPushingUser
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: temp_release_notes
          OWNER: yourGitHubOrganisation
          REPO_NAME: patent-view-api
          SKIP_MD: README.md
